apiVersion: v1
kind: Service
metadata:
  name: api-client-service
  namespace: selectgearmotors-ns
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb" # Network Load Balancer
    # Para Load Balancer interno (opcional)
    # service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    aws.servicediscovery.endpoint: "enabled"
    cloudmap.amazonaws.com/namespace: "selectgearmotors.local" # Namespace no AWS Cloud Map
    cloudmap.amazonaws.com/service: "api-client"       # Nome do serviço no Cloud Map
    cloudmap.amazonaws.com/enable: "true"             # Habilitar registro no Cloud Map
spec:
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 80        # Porta externa do LoadBalancer
      targetPort: 9914   # Porta do Pod
  selector:
    app: selectgearmotors-client-api
